import { requireUser } from "@/lib/auth";import { daySnapshot,audit,settingsMap } from "@/lib/business";import { query } from "@/lib/db";import { ok,fail } from "@/lib/api";
function admin(user){if(user.role!=="Super Admin")throw new Error("Super Admin permission required.")}
export async function GET(req){try{const u=await requireUser();const date=new URL(req.url).searchParams.get("date")||new Date().toISOString().slice(0,10);return ok(await daySnapshot(date,u.id));}catch(e){return fail(e.message,e.message==="UNAUTHORIZED"?401:500)}}
export async function POST(req){try{const u=await requireUser();const b=await req.json();const snap=await daySnapshot(b.date,u.id);const actual=Number(b.actual);if(!Number.isFinite(actual)||actual<0)throw new Error("Enter a valid counted cash amount.");const variance=actual-snap.expected;await query(`update cash_days set expected_closing=$1,actual_cash=$2,variance=$3,status='FINALIZED',finalized_by=$4,finalized_at=now(),manager_note=$5,updated_at=now() where business_date=$6`,[snap.expected,actual,variance,u.id,b.note||"",b.date]);await audit(u.id,"FINALIZE_DAY","cash_day",null,b.date,`Actual cash ${actual}`);return ok({expected:snap.expected,variance});}catch(e){return fail(e.message,e.message==="UNAUTHORIZED"?401:400)}}
export async function PATCH(req){try{const u=await requireUser();admin(u);const b=await req.json(),date=String(b.date||"").slice(0,10);const snap=await daySnapshot(date,u.id);
  if(b.action==="reopen"){if(snap.day.status!=="FINALIZED")throw new Error("This day is already open.");await query(`update cash_days set status='OPEN',expected_closing=null,actual_cash=null,variance=null,finalized_by=null,finalized_at=null,updated_at=now() where business_date=$1`,[date]);await audit(u.id,"REOPEN_DAY","cash_day",null,date,b.reason||"Reopened by administrator");return ok({ok:true})}
  if(b.action==="opening"||b.action==="resetOpening"){let opening=Number(b.opening);if(b.action==="resetOpening"){const prev=await query("select actual_cash from cash_days where business_date<$1 and status='FINALIZED' and actual_cash is not null order by business_date desc limit 1",[date]);const settings=await settingsMap();opening=prev.rows[0]?Number(prev.rows[0].actual_cash):Number(settings.initial_opening_cash||0)}if(!Number.isFinite(opening)||opening<0)throw new Error("Enter a valid opening cash amount.");const expected=opening+Number(snap.cashIn)-Number(snap.cashOut),variance=snap.day.status==="FINALIZED"?Number(snap.day.actual_cash)-expected:null;await query("update cash_days set opening_cash=$1,expected_closing=case when status='FINALIZED' then $2 else expected_closing end,variance=case when status='FINALIZED' then $3 else variance end,updated_at=now() where business_date=$4",[opening,expected,variance,date]);await audit(u.id,b.action==="resetOpening"?"RESET_OPENING":"EDIT_OPENING","cash_day",null,date,`Opening cash ${opening}`);return ok({ok:true,opening})}
  throw new Error("Invalid day action.");
}catch(e){return fail(e.message,e.message==="UNAUTHORIZED"?401:e.message.includes("permission")?403:400)}}
